### ISSUE TITLE
返回类型错误

### ISSUE THREAD

**Issue by Pokoai** [IfanTsai/c51-lib#3]
https://github.com/IfanTsai/c51-lib/blob/52365b80879a3db0e0779a03f29e59f9aa33e3dc/include/key.h#L8

既然会返回 -1 ，那么返回类型为无符号的 uchar 就不对了，应该改为 char。

**Comment by IfanTsai** [comment]
的确有问题，好几年前写的代码了，要不你提个 PR 改下？

**Comment by IfanTsai** [comment]
merged
